s=str(input('Introduceti sirul de caractere'))
print('Numarul de aparitii ale caracterului A in sirul s=',s.count('A'))
print('Sirul obtinut prin substituirea caracterului A prin caracterul *',s.replace('A','*'))
a=list(s)
a.remove('B')
a=''.join(a)
print('Sirul obtinut prin radierea din sirul S a tuturor aparitiilor caracterului B',a)
print('numarul de aparitii ale silabei MA in sirul S',s.count('MA'))
print('Sirul otinut prin substituirea tuturor aparitii in sirul S a silabei MA prin silaba TA',s.replace('MA','TA'))
b=list(s)
b.remove('TO')
b=''.join(b)
print('Sirul obtinut prin radierea din sirul S a tuturor aparitiilor caracterului TO ',b)
print('Scrierea inversa a sirului S',s[::-1])